// AUTH TYPES
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

// USERS TYPES
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAIL = 'GET_USERS_FAIL'
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED'
export const RESEND_TOKEN_SUCCESS = 'RESEND_TOKEN_SUCCESS'
export const RESEND_TOKEN_FAIL = 'RESEND_TOKEN_FAIL'
export const VERIF_TOKEN_SUCCESS = 'VERIF_TOKEN_SUCCESS'
export const VERIF_TOKEN_FAIL = 'VERIF_TOKEN_FAIL'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'

// ELECTION TYPES
export const CREATE_ELECTION_SUCCESS = 'CREATE_ELECTION_SUCCESS'
export const CREATE_ELECTION_FAILED = 'CREATE_ELECTION_FAILED'
export const EDIT_ELECTION_SUCCESS = 'EDIT_ELECTION_SUCCESS'
export const GET_ELECTIONS_SUCCESS = 'GET_ELECTIONS_SUCCESS'
export const DELETE_ELECTION_SUCCESS = 'DELETE_ELECTION_SUCCESS'
export const GET_ELECTION_BY_ID = 'GET_ELECTION_BY_ID'
export const VOTE_SUCCESS = 'VOTE_SUCCESS'
export const ADD_CANDIDATE_TO_ELECTION_SUCCESS =
  'ADD_CANDIDATE_TO_ELECTION_SUCCESS'
export const REMOVE_CANDIDATE_FROM_ELECTION_SUCCESS =
  'REMOVE_CANDIDATE_FROM_ELECTION_SUCCESS'
export const ELECTION_ERROR = 'ELECTION_ERROR'
export const GET_USER_ELECTION_SUCCESS = 'GET_USER_ELECTION_SUCCESS'
export const ADD_USER_VOTED_ELECTION = 'ADD_USER_VOTED_ELECTION'
export const DELETE_USER_VOTE = 'DELETE_USER_VOTE'

// CANDIDATE TYPES
export const ADD_CANDIDATE_SUCCESS = 'ADD_CANDIDATE_SUCCESS'
export const ADD_CANDIDATE_FAILED = 'ADD_CANDIDATE_FAILED'
export const REMOVE_CANDIDATE = 'REMOVE_CANDIDATE'
export const SET_CANDIDATES = 'SET_CANDIDATES'
export const CANDIDATE_ERROR = 'CANDIDATE_ERROR'

// MESSAGES TYPES
export const SET_MESSAGE = 'SET_MESSAGE'
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE'
